config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/login', to:'sessions#destroy'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email = email.downcase}
#activerecocrdのcallbackメソッドを使って
#ユーザーをDBに保存する前にemail属性を強制的に小文字に変換している
  validates :name, presence: true,
                   length:{maximum: 50}
  VALD_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length:{maximum: 252},
                    format:{with: VALD_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
#case_sensitiveは小文字と大文字を区別するオプション
#falseにすることで区別しないとしている
#uniquenessはオプションを付けると自動的にuniqueness: trueと判断する
  has_secure_password
#has_secure_passwordメソッドを追記すればセキュアなパスワードの実装完了
  validates :password, presence: true,
                       length:{minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 def hello
  render html:"hello,world"
 end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
    else
     flash[:danger] = 'Invalid email/password combination'
     render"new"
    end

  end

  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    #@user = User.new(params[:user])マスアサインメントの脆弱性より、←はダメ
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the sample app!"
      redirect_to @user
    else
      render 'new'
    end
  end

private
 def user_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path %></li>
        <li><%= link_to "Help",help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message|%>
        <%= content_tag(:div,message,class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      "<%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id = "error_explanation">
  <div class = "alert alert-danger">
    The form contains <%= pluralize(@user.errors.count,"error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/help.html.erb
<h1>help</h1>
<p>This is help page.</p>

app/views/static_pages/home.html.erb
<h1>home</h1>
<p>Welcome to sample app. This sample app is my portfolio.</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class = "row">
   <div class = "col-md-6 col-md-offset-3">
     <%= form_for(@user,url: signup_path) do |f| %>
     <%= render 'shared/error_messages'%>

       <%= f.label :name %>
       <%= f.text_field :name, class:'form-control' %>

       <%= f.label :email %>
       <%= f.text_field :email, class:'form-control' %>

       <%= f.label :password %>
       <%= f.text_field :password, class:'form-control' %>

       <%= f.label :password_confirmation, "Confirmation" %>
       <%= f.text_field :password_confirmation, class:'form-control' %>

       <%= f.submit "Create my account",class: "btn btn-primary" %>
     <% end %>
   </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>